name: Manual Test & Build

on:
  workflow_dispatch:
    inputs:
      run_tests:
        description: 'Run tests'
        required: true
        default: true
        type: boolean
      create_package:
        description: 'Create VSIX package'
        required: true
        default: true
        type: boolean
      os_matrix:
        description: 'Operating systems to test'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
        - 'ubuntu-latest'
        - 'windows-latest'
        - 'macos-latest'
        - 'all'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Set OS Matrix
      id: set-matrix
      run: |
        if [ "${{ github.event.inputs.os_matrix }}" = "all" ]; then
          echo 'matrix=["ubuntu-latest", "windows-latest", "macos-latest"]' >> $GITHUB_OUTPUT
        else
          echo 'matrix=["${{ github.event.inputs.os_matrix }}"]' >> $GITHUB_OUTPUT
        fi

  test-and-build:
    needs: setup
    strategy:
      matrix:
        os: ${{ fromJSON(needs.setup.outputs.matrix) }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Lint
      run: npm run lint
      
    - name: Compile
      run: npm run compile
      
    - name: Run tests (Linux)
      if: github.event.inputs.run_tests == 'true' && runner.os == 'Linux'
      run: xvfb-run -a npm test
      
    - name: Run tests (macOS/Windows)
      if: github.event.inputs.run_tests == 'true' && runner.os != 'Linux'
      run: npm test
      
    - name: Package extension
      if: github.event.inputs.create_package == 'true'
      run: npm run package
      
    - name: Upload VSIX artifact
      if: github.event.inputs.create_package == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: extension-vsix-${{ matrix.os }}
        path: '*.vsix'
